GET http://localhost:8000/planets HTTP/1.1
###
GET http://localhost:8000/launches HTTP/1.1
###
POST http://localhost:8000/launches HTTP/1.1
content-type: application/json

{
    "mission":"ZTM160",
    "rocket":"ZTM Starship",
    "target":"Kepler-62 f",
    "launchDate":"July 1, 2028"
}