GET http://localhost:8000/planets HTTP/1.1
###
GET http://localhost:8000/launches HTTP/1.1
###
POST http://localhost:8000/launches HTTP/1.1
content-type: application/json

{
    "mission":"KO-1",
    "rocket":"ZTM Starship",
    "target":"Kepler-62 f",
    "launchDate":"July 1, 2028"
}
###
DELETE http://localhost:8000/launches/105 HTTP/1.1
content-type: application/json
###
POST https://api.spacexdata.com/v4/launches/query HTTP/1.1
content-type: application/json

{
    "query":{},
    "options":{
        "populate":[
           {
            "path":"rocket",
            "select":{
                "name":1
            }
           },
           {
            "path":"payloads",
            "select":{
                "customers":1
            }
           }

        ]
    }
}
###
GET http://localhost:8000/v1/launches?limit=5&page=1 HTTP/1.1